# Generated by Django 5.0.6 on 2024-05-10 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConferenceRoom',
            new_name='Sala',
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('komentarz', models.TextField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.sala')),
            ],
            options={
                'unique_together': {('sala', 'data')},
            },
        ),
    ]
